In [1]:
import pandas as pd

In [10]:
df = pd.read_csv('winequality-red.csv', sep=';')

df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [12]:
df = df.drop(columns='quality')

df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
# Standardizing the features
x = StandardScaler().fit_transform(df)

In [16]:
print(x)

[[-0.52835961  0.96187667 -1.39147228 ...  1.28864292 -0.57920652
  -0.96024611]
 [-0.29854743  1.96744245 -1.39147228 ... -0.7199333   0.1289504
  -0.58477711]
 [-0.29854743  1.29706527 -1.18607043 ... -0.33117661 -0.04808883
  -0.58477711]
 ...
 [-1.1603431  -0.09955388 -0.72391627 ...  0.70550789  0.54204194
   0.54162988]
 [-1.39015528  0.65462046 -0.77526673 ...  1.6773996   0.30598963
  -0.20930812]
 [-1.33270223 -1.21684919  1.02199944 ...  0.51112954  0.01092425
   0.54162988]]


In [17]:
import numpy as np

In [54]:
xt = x.T

cov_mat = np.cov(xt)

cov_mat;

In [21]:
corr_mat = np.corrcoef(xt)

corr_mat

array([[ 1.        , -0.25613089,  0.67170343,  0.11477672,  0.09370519,
        -0.15379419, -0.11318144,  0.66804729, -0.68297819,  0.18300566,
        -0.06166827],
       [-0.25613089,  1.        , -0.55249568,  0.00191788,  0.06129777,
        -0.01050383,  0.07647   ,  0.02202623,  0.23493729, -0.26098669,
        -0.20228803],
       [ 0.67170343, -0.55249568,  1.        ,  0.14357716,  0.20382291,
        -0.06097813,  0.03553302,  0.36494718, -0.54190414,  0.31277004,
         0.10990325],
       [ 0.11477672,  0.00191788,  0.14357716,  1.        ,  0.05560954,
         0.187049  ,  0.20302788,  0.35528337, -0.08565242,  0.00552712,
         0.04207544],
       [ 0.09370519,  0.06129777,  0.20382291,  0.05560954,  1.        ,
         0.00556215,  0.04740047,  0.20063233, -0.26502613,  0.37126048,
        -0.22114054],
       [-0.15379419, -0.01050383, -0.06097813,  0.187049  ,  0.00556215,
         1.        ,  0.66766645, -0.02194583,  0.0703775 ,  0.05165757,
        -0.069

In [29]:
eig = np.linalg.eig(corr_mat)

eig_vals = eig[0]
eig_vecs = eig[1]

In [38]:
eig_vals_sorted = -np.sort(-eig_vals)
eig_vecs_sorted = eig_vecs[:, eig_vals.argsort()[::-1]]

In [53]:
eig_vals;

In [40]:
eig_vals_sorted

array([3.09913244, 1.92590969, 1.55054349, 1.21323253, 0.95929207,
       0.65960826, 0.58379122, 0.4229567 , 0.34464212, 0.18133317,
       0.05955831])

In [52]:
eig_vecs;

In [42]:
eig_vecs_sorted

array([[ 0.48931422, -0.11050274, -0.12330157, -0.22961737, -0.08261366,
         0.10147858, -0.35022736, -0.17759545,  0.19402091, -0.24952314,
        -0.63969145],
       [-0.23858436,  0.27493048, -0.44996253,  0.07895978,  0.21873452,
         0.41144893, -0.5337351 , -0.07877531, -0.1291103 ,  0.36592473,
        -0.0023886 ],
       [ 0.46363166, -0.15179136,  0.23824707, -0.07941826, -0.05857268,
         0.06959338,  0.10549701, -0.37751558, -0.38144967,  0.62167708,
         0.0709103 ],
       [ 0.14610715,  0.27208024,  0.10128338, -0.37279256,  0.73214429,
         0.04915555,  0.29066341,  0.29984469,  0.00752295,  0.09287208,
        -0.18402996],
       [ 0.21224658,  0.14805156, -0.09261383,  0.66619476,  0.2465009 ,
         0.30433857,  0.37041337, -0.35700936,  0.11133867, -0.21767112,
        -0.05306532],
       [-0.03615752,  0.51356681,  0.42879287, -0.04353782, -0.15915198,
        -0.01400021, -0.11659611, -0.2047805 ,  0.63540522,  0.24848326,
         0.051

In [43]:
sum_eig_vals = np.sum(eig_vals_sorted)

sum_eig_vals

11.0

In [45]:
np.true_divide(eig_vals_sorted, sum_eig_vals)

np.sum(np.true_divide(eig_vals_sorted, sum_eig_vals))

0.9999999999999998

In [47]:
np.true_divide(eig_vals_sorted*100, sum_eig_vals)

# np.sum(np.true_divide(eig_vals_sorted*100, sum_eig_vals))

array([28.17393128, 17.50826991, 14.0958499 , 11.02938664,  8.72083701,
        5.99643877,  5.3071929 ,  3.84506091,  3.13311015,  1.64848333,
        0.5414392 ])

In [48]:
np.cumsum(np.true_divide(eig_vals_sorted*100, sum_eig_vals))

array([ 28.17393128,  45.68220118,  59.77805108,  70.80743772,
        79.52827474,  85.52471351,  90.83190641,  94.67696732,
        97.81007747,  99.4585608 , 100.        ])

In [49]:
from sklearn.decomposition import PCA

pca = PCA(n_components=5)

principalComponents = pca.fit_transform(x)

principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2', 'principal component 3', 'principal component 4', 'principal component 5'])

In [51]:
principalDf.head()

principal component 1  principal component 2  principal component 3  \
0              -1.619530               0.450950              -1.774454   
1              -0.799170               1.856553              -0.911690   
2              -0.748479               0.882039              -1.171394   
3               2.357673              -0.269976               0.243489   
4              -1.619530               0.450950              -1.774454   

   principal component 4  principal component 5  
0               0.043740               0.067014  
1               0.548066              -0.018392  
2               0.411021              -0.043531  
3              -0.928450              -1.499149  
4               0.043740               0.067014